Criterion/Types.hs

The example code for `env` has been corrected so that it's both syntactically correct and also type-checks.

Fix example in 'env' docs

---

Criterion/Main/Options.hs

Prior to this patch it was basically impossible, without looking at the source code.

Improve help and error message of --match: Show values alternatives

---

Criterion/Main.hs

Previously Criterion.Main.Options exported the Mode type which is great
when you want to add a few domain-specific options to your benchmark.
Unfortunately, there was no exported function to actually run the
benchmark as defaultMain would have done. This adds precisely this
function.

Criterion.Main: Factor out and export runMode

---

Criterion/IO/Printf.hs

This ensures that messages will appear in a timely manner even when piped through a program like `tee`.

Flush stdout and stderr so messages appear immediately even when piped

---

cbits/cycles.c

Tested on i386 and x86_64 Linux.

cbits/cycles.c: Restore support for 32 bit Intel CPUs

---

Criterion/Internal.hs

With ReadWriteMode Haskell opens the file but doesn't truncate the contents. That means if we have a file there from before, we end up overwriting the start, and if the file was longer, we end up with corrupt JSON. Only visible if you run the test suite multiple times, and somewhat non-deterministic since it requires longer times (when printed in exponential format), followed by shorter times.

#107, open the output file in the write mode

---

README.markdown

GitHub link processing magic takes care of adding the right repo & branch.

Fix link to examples in README.markdown

---

www/tutorial.md

The types in the tutorial for whnfIO and nfIO are pre 1.0.0.1

Update tutorial to reflect changes to nfIO and whnfIO

---

Criterion/Types.hs

For some reason, it's not currently implemented, and it's resulted in [at least one sporadic failure](https://travis-ci.org/RyanGlScott/text-show/jobs/151838151#L1835) for me during benchmarking. I'm not sure _why_ it's sporadic, but luckily it's an easy fix.

Implement get for Binary Regression instance

---

changelog.md
criterion.cabal

This fixes two things:
1. The current Hackage version of `criterion` is 1.1.4.0, but the repo is behind that. This brings the version in the repo up to date.
2. As noted in #126, the changelog doesn't mention 1.1.4.0, and moreover, the amount of changes that it _does_ mention is a bit lacking (for example, it didn't mention a change in the default template that resulted in #127). This PR attempts to mention more of the highlights of the 1.1.4.0 release.

Give more comprehensive changelog for 1.1.4.0

---

app/Options.hs
criterion.cabal

Quick commit in-between work and lack of old GHC's to test with lead to the previously merged gen-report breaking the Travis tests. This should fix all those issues. See #142

Fixes for the build problems introduced by the earlier gen-report merge.

---

Criterion.hs
Criterion/Internal.hs
Criterion/Main.hs
Criterion/Main/Options.hs
Criterion/Measurement.hs
Criterion/Monad/Internal.hs
Criterion/Types.hs
criterion.cabal
stack.yaml
tests/Cleanup.hs

This patch adds support for per run benchmark allocation/cleanup of
environment, allocation/cleanup per batch of runs, and adds cleanup support for
the existing `env` function.
Fixes #79, #134, #135. Obsoletes #124.

Add new methods for allocating and cleaning up benchmark environments.

---

Criterion/Measurement.hs
changelog.md
examples/Overhead.hs

This introduces a backwards-compatible `GCStatistics` type, as well as functions supporting it, intended to replace the now-deprecated `GCStats` interface.
Fixes #146.

Fix #146 by introducing GCStatistics

---

Criterion/Report.hs
changelog.md
criterion.cabal

Previously, if you passed in a custom mustache template via `--template` and it failed to substitute in a variable correctly, `criterion` would silently ignore it. This PR leverages new features in `microstache` to make the failure more explicit. For instance, if you have a template that tries to substitute in `{{{jsonx}}}` instead of `{{{json}}}`, it will now emit this warning:
```
criterion: warning:
Referenced value was not provided, key: jsonx
```
Fixes #127.

Emit mustache template warnings

---

Criterion/Report.hs
changelog.md
templates/default.tpl

`statistics-0.14` changed some details surrounding the `Estimate` data type. In particular, the confidence level, lower bound, and upper bound are no longer fields of `Estimate`, but instead must be computed. We failed to adapt the default HTML report to these changes, which led to the displayed results being just plain wrong.
Fixes #153.

Fix #153 by adapting to the statistics-0.14 API more carefully in HTML reports

---

Criterion/Types.hs
criterion.cabal

This will be needed in GHC 8.4 due to the Semigroup/Monoid proposal.

Add Semigroup instance for Outliers

---

.travis.yml
Criterion/EmbeddedData.hs
Criterion/Report.hs
criterion.cabal
templates/default.tpl

This should make it simpler to create portable `criterion` binaries. Resolves #45.

Resolve #45 by adding an -fembed-data-files flag 

---

Criterion/Measurement.hs

From `GHC.Stats` documentation for `GCStats` in base 4.10.0.0 on [hackage](https://hackage.haskell.org/package/base-4.10.0.0/docs/GHC-Stats.html):
> Statistics about memory usage and the garbage collector. Apart from currentBytesUsed and currentBytesSlop all are cumulative values since the program started.
For base >= 4.10.0 criterion chooses to use the new `RTSStats` type for GC measurements, but uses `GCDetails` for bytes allocated, bytes copied, and GC CPU times. This gave bogus results when, for instance, regressing allocated over iters. This program:
```Haskell
import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import Criterion
import Criterion.Main
makeBS :: Int -> ByteString
makeBS n = BS.replicate n 0
benchmarks :: [Benchmark]
benchmarks = [
bench "make" …
```

Fix GC/RTS stats for base >= 4.10.0

---

Criterion/Measurement.hs
Criterion/Types.hs

performGC before getting RTS/GC stats
The deprecated getGCStats had some nice documentation: "If you would
like your statistics as recent as possible, first run a performGC"
This is sadly missing from getRTSStats but I believe it still holds.
When regressing allocated over iters, I'd see a believable slope, but an
unbelievable y intercept, something like -300000 when the slope is 150
or so. That's because the first hundred or so measurements were 0 for
bytes allocated, as the RTS didn't bother to run a GC before the RTS
stats were sampled.
Now we do 3 samples:
1. performGC before the first one, to ensure it's up-to-date.
2. Do the second one after the action, without a performGC, so we can
get legit readings on the GC-related stats.
3. performGC and then sample again, so we can get …

performGC before getting RTS/GC stats

---

Criterion/Measurement.hs
changelog.md

Before change:
benchmarking perRun
measurement took 231495 s (60 hours!!!)
analysing with 1000 resamples
bootstrapping with 13 of 22 samples (59%)
time                 3.112 ms   (3.102 ms .. 3.122 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 3.119 ms   (3.111 ms .. 3.122 ms)
std dev              10.00 μs   (5.617 μs .. 16.74 μs)
found 1 outliers among 13 samples (7.7%)
1 (7.7%) low severe
variance introduced by outliers: 4% (slightly inflated)
After:
benchmarking perRun
measurement took 5.135 s
analysing with 1000 resamples
bootstrapping with 33 of 42 samples (78%)
time                 3.120 ms   (3.116 ms .. 3.124 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 3.117 ms   (3.111 ms .. 3.120 ms)
std dev              11.95 μs   (6.974 μs .. 20.56 μs)
found 3 …

Fix per-run combine time (fixes #181)

---

Criterion/Types.hs
Criterion/Types/Internal.hs
changelog.md

This is finished in theory, but will need to be documented/cleaned up for merge.
It can be tested with my development wrapper [here](https://github.com/patrickdoc/criterion-bug). You can clone, pull the crriterion submodule, and use `run-versions.sh` to run `example/Small.hs` under various optimizations. I've attached output from my computer to save time though.
[comparison.txt](https://github.com/bos/criterion/files/1697880/comparison.txt)
The biggest highlight is this comparison:
```
-- Old with -O2
17,911,308,968 bytes allocated in the heap
-- New with -O2
293,624,648 bytes allocated in the heap
```
This does have an impact on measured times. For instance, `whnf id x` drops to ~6ns from ~9ns.
The checklist looks like so:
Most of these problems are fixed by small tweaks and `NOINLINE` …

Remove allocation from inner loops (fixes #183)

---

stack.yaml

It defaults to using `optparse-applicative-0.14.0.0`. So the `extra-dep` is not necessary anymore.

Bump the stack LTS version to 10.5

---

Criterion/Measurement.hs
changelog.md

Using the example from issue #185...
Before:
```
benchmarking small-fast
bootstrapping with 39 of 312 samples (12%)
time                 6.877 ns   (6.724 ns .. 7.062 ns)
0.996 R²   (0.994 R² .. 0.997 R²)
mean                 6.898 ns   (6.758 ns .. 7.034 ns)
std dev              448.3 ps   (391.7 ps .. 540.9 ps)
variance introduced by outliers: 83% (severely inflated)
benchmarking large-slow
measurement took 69.20 s
bootstrapping with 16 of 289 samples (5%)
time                 6.380 ns   (6.241 ns .. 6.542 ns)
0.996 R²   (0.994 R² .. 0.998 R²)
mean                 6.453 ns   (6.267 ns .. 6.668 ns)
std dev              414.9 ps   (320.0 ps .. 548.2 ps)
variance introduced by outliers: 82% (severely inflated)
354,607,016 bytes allocated in the heap
74,880,263,968 bytes copied during GC …
```

Decrease impact of gc on benchmark performance (fixes #185)

---

changelog.md
criterion-measurement/src/Criterion/Measurement.hs
examples/Overhead.hs

My comment before was slightly mistaken. As you said, it's already explicitly stated in the docs that `initializeTime` must be called before using `getTime`.
So the changes I made were just adding `initializeTime` in the appropriate places. Let me know if there's anything I missed.

Call initializeTime before getTime in Measurement.hs; fixes issue #195

---

changelog.md
criterion.cabal

This should be the last one of these dependency-reduction PRs for a while. Hopefully.

Only incur a dependency on fail on old GHCs.

---

templates/default.tpl

Proposed fix for https://github.com/bos/criterion/issues/202

Fix broken html report when benchmark names contain '\''

---

README.markdown

GitHub proxies all images (see their docs on [anonymized image URLs](https://help.github.com/articles/about-anonymized-image-urls/), and it seems www.serpentine.com isn't sending a Cache-Control: no-cache header for the screenshot and thus it isn't proxied correctly.
Fixed quite simply by using the screenshot in the repo; you can see this working at https://github.com/tchajed/criterion/tree/fix-readme-screenshot.

Fix URL for benchmark screenshot

---

templates/default.tpl

* zooming all the way out resets to the default view instead of
continuing to zoom out towards less useful views containing a lot of
empty space.
* panning all the way to the right resets to the default view in which
zero is left-aligned instead of continuing to pan and allowing the
bars to detach from the edge of the graph.
* panning and zooming only affects the x axis, so all the results remain
in frame.
You can try it for yourself [here](http://gelisam.com/files/criterion-constrained-navigation.html), and compare it with [the current behaviour](http://gelisam.com/files/criterion-unconstrained-navigation.html). Note that the [demo](http://www.serpentine.com/criterion/fibber.html) from the readme uses an older version which doesn't support zooming at all.
Alternatively, here's a picture …

constrain the navigation to make it easier to get useful views.

---

www/tutorial.md

I pasted the tutorial into a project to get started with criterion and got this confusing error message:
```
test.hs:9:5: error:
• Occurs check: cannot construct the infinite type:
t1 ~ Integer -> t1
Expected type: t1 -> p1
Actual type: (Integer -> t1) -> p1
• In an equation for ‘fib’:
fib m
| m < 0 = error "negative!"
| otherwise = go m
where
go 0 = 0
go 1 = 1
go n = go (n -1) + go (n -2)
• Relevant bindings include go :: t1 -> p1 (bound at test.hs:9:5)
```
Which occurs when NegativeLiterals is enabled. An easy fix is to add spaces around the `-`. 
Also, I at least personally think that this looks a little better, and matches the style of `m < 0` vs `m<0` earlier in the exampl ecode.

Make tutorial compatible with NegativeLiterals

---

Criterion/Report.hs
changelog.md

Newlines wreak havoc on JavaScript strings in the default HTML report. We could attempt to turn newlines into properly escaped JS strings before compiling the Mustache template, but this is overkill, since the string will be rendered as if the newlines were simple spaces anyway. As a result, we simply turn all newlines into spaces and emit a warning.
Fixes #224.

Warn if report names contains newlines

---

Criterion/Report.hs
templates/criterion.js
templates/default.tpl

By crafting a malicious string it was quite easy to escape the HTML
attribute that contained the JSON report data allowing injection of
arbitrary HTML using the report names.
This commit aims to mitigate the breakage of the reports when report names
contain unexpected characters. The JSON data is moved to a <script> tag and
the content is escaped by replacing significant HTML characters with their
corresponding JSON escape sequences. The '<' character is replaced with the
sequence "\u003c", '&' is replaced with "\u0026" and so on.
The processing of `/` is still not ideal, if a report name contains that character
then it is treated as a group separator.

Escape JSON to avoid parsing the content as HTML

---

criterion-measurement/src/Criterion/Measurement/Types.hs

Its first argument is supposed to be a function which reduces the result to normal form. Specifying its type as 'a -> ()', rather than 'a -> b' conveys this intention better. Also, presently nfIO' is an internal function used only by nfIO, which uses 'rnf' as a reducer.
Anyway, this is a really minor thing. I was looking at this file for something and happened to notice this.

Use a more precise type for nfIO'

---

criterion-measurement/cbits/cycles.c
criterion-measurement/cbits/time-osx.c
criterion-measurement/changelog.md

This applies two tweaks to `cycles.c` and `time-osx.c` to ensure that `criterion_rdtsc` and `criterion_gettime` work on all versions of macOS, regardless of the architecture being used. In particular, this is required to make `criterion-measurement` compile and run on Apple silicon.
Fixes #238.

Make C code work on Intel- and ARM-based Macs

---

Criterion/Main/Options.hs

Previously, the `config` function would ignore the value of `regressions` that specified (e.g., via the `Config` argument of
`defaultMain`). Since `--regressions` is an argument that is allowed to be passed multiple times, it's somewhat awkward to specify a default argument for it. I adopt a similar approach to what the old `arguments1` function in `optparse-applicative` did (see https://github.com/pcapriotti/optparse-applicative/commit/700e07b0751d02fec938af67d1f917e60974a601).
Fixes #244.

Use default value for `regressions` when creating `config`

---

Criterion/Report.hs
examples/Quotes.hs
examples/criterion-examples.cabal

This PR removes the overzealous "for good measure" escape of the JSON data that caused issues when using quotes in the benchmark names.
Closes #235

escape: remove too agressive JSON escaping

---

Criterion/Report.hs

As a follow up to #248 I added some documentation about why \0 is escaped and what to do if the escaped string is to be used in an HTML attribute.
In criterion the JSON-encoded string is used in a `<script>` tag as text (which is indicated in the comment) but I think it would be improper to leave the attribute case unclear, especially since the previous version tried to escape for this use case as well.

Expand documentation of `escapeJSON`

---

changelog.md
criterion-measurement/changelog.md
criterion-measurement/criterion-measurement.cabal
criterion-measurement/src/Criterion/Measurement.hs
criterion-measurement/src/Criterion/Measurement/Types.hs
criterion.cabal
tests/Tests.hs

Adds the "peak mb allocated" to the json output for #256.
I wasn't sure which "max mb" stat we wanted to take here, so I took the final `endPostGC` one. In my testing `endPostGC`, `endStatsPreGC`, and `startStats` were all the same, in any case. 
```haskell
measAllocated         = diff endPostGC gcStatsBytesAllocated
, measPeakMbAllocated   = gcStatsPeakMegabytesAllocated endPostGC
```
Example:
```json5
{
"reportMeasured": [
[
4.930255000090256e-3,
1.1697070000000007e-3,
11361858,
1,
1236872,
3,                /* peakMbAllocated */
1,
189848,
4.644875e-3,
8.848910000000001e-4,
2.9445099999999983e-4,
2.93705e-4
]
],
...
"reportKeys": [
"time",
"cpuTime",
"cycles",
"iters",
"allocated",
"peakMbAllocated",
"numGcs",
"bytesCopied",
"mutatorWallSeconds",
"mutatorCpuSeconds",
"gcWallSeconds", …
```

Add peak bytes allocated field to Measured

---

Criterion/Main/Options.hs
changelog.md

I thought I had fixed #168 in 45c135d67980c3690c3ad8f01c45667f2beab33c, but I had overlooked that the `Parser` for `--match` appears on both sides of a `(<|>)` expression, thereby duplicating its `--help` text. A somewhat heavy-handed but serviceable solution is to pair up the common sub-`Parsers` between the `Run` and `RunIters` `Mode`s as much as possible, which prevents the `--match` `Parser` from ever being run more than once. I've left a lengthy comment explaining how this works.

Fix #168 (again) by factoring out common sub-`Parser`s

---

.gitattributes

This should update the project's language bar and tag it as a Haskell project (currently, Criterion is tagged as an HTML project).
This is what I mean (after applying this PR):

Remove entries from www/ directory from the linguist statistics

---

.github/workflows/haskell-ci.yml
Criterion/Main/Options.hs
Criterion/Main/Options/Internal.hs
changelog.md
criterion-measurement/criterion-measurement.cabal
criterion.cabal
examples/criterion-examples.cabal

This adds the necessary CPP to support building `criterion` with `optparse-applicative-0.18.*` as well as older versions of the library. In a future, major release of `criterion`, we will require `optparse-applicative-0.18.*` as the minimum and explicitly depend on `prettyprinter`.

Support building with `optparse-applicative-0.18.*`

---

README.markdown

README: Use GitHub-Flavored Markdown, not HTML, for hyperlinks

---

examples/ConduitVsPipes.hs

Very small change; but she goes by Gabriella now, and it would be good to correct the credit given in this example.

Correct contributor name for ConduitVsPipes example

---

criterion-measurement/cbits/cycles.c

We can read the `cntvct_el0` register to observe the CPU clock. It is a single instruction and has barely any overhead.

Support non-Darwin, non-Linux, aarch64 platforms
